name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '3 2 * * SUN'
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm test --coverage
      - run: pnpm run build
